#! /bin/sh

bspc monitor -d www code docs

bspc config border_width      			  2
bspc config window_gap        			  8
bspc config top_padding		  			  19
bspc config bottom_padding	  			  0
bspc config left_padding	  			  0
bspc config right_padding	  			  0

bspc config split_ratio           		  0.52
bspc config borderless_monocle    		  true
bspc config gapless_monocle       		  false
bspc config focus_follows_pointer 		  true
bspc config normal_border_color   		  '#222222'
bspc config focused_border_color  		  '#d81860'   #'#ae81ff'
bspc config presel_border_color   		  '#ae81ff'

bspc config auto_cancel		 			  true
bspc rule -a tilda                        floating=on   focus=on   locked=on
bspc rule -a irssi                        follow=on
bspc rule -a mplayer                      focus=on
bspc rule -a feh                          floating=on
bspc rule -a xpad                         floating=on   foxus=off
bspc rule -a synfigstudio                 floating=on
bspc rule -a gtksu                        floating=on
bspc rule -a vlc                          floating=on
bspc rule -a grub-customizer              floating=on
bspc rule -a gparted                      foating=on
bspc rule -a ranger                       foating=off
bspc rule -a ncmpcpp                      desktop=mpd
bspc rule -a roxterm                      focus=off locked=on manage=off
/home/aish/.config/bspwm/panel &
