#! /bin/sh

bspc monitor -d www term docs code beats

bspc config border_width      			  1
bspc config window_gap        			  -1
bspc config top_padding		  			  20
bspc config bottom_padding	  			  1
bspc config left_padding	  			  1
bspc config right_padding	  			  1

bspc config split_ratio           		  0.52
bspc config borderless_monocle    		  true
bspc config gapless_monocle       		  false
bspc config focus_follows_pointer 		  true
bspc config normal_border_color   		  '#444444'
bspc config focused_border_color  		  '#81d3d3'
bspc config presel_border_color   		  '#B7CE42'

bspc config auto_cancel		 			  true
bspc rule -a tilda floating=on focus=on locked=on
bspc rule -a irssi follow=on
bspc rule -a mplayer focus=on
bspc rule -a feh floating=on
bspc rule -a gtksu floating=on
bspc rule -a vlc floating=on
bspc rule -a grub-customizer floating=on
bspc rule -a gparted foating=on
bspc rule -a ranger foating=off
bspc rule -a ncmpcpp desktop=mpd
/home/aish/.config/bspwm/panel &
