#! /bin/sh

bspc monitor -d term

bspc config border_width      			  1
bspc config window_gap        			  -1
bspc config top_padding		  			  20
bspc config bottom_padding	  			  1
bspc config left_padding	  			  1
bspc config right_padding	  			  1

bspc config split_ratio           		  0.52
bspc config borderless_monocle    		  true
bspc config gapless_monocle       		  true
bspc config focus_follows_pointer 		  true
bspc config normal_border_color   		  '#171717'
bspc config focused_border_color  		  '#FEA63C' 
bspc config presel_border_color   		  '#B7CE42'
bspc config focused_locked_border_color   '#222222'
bspc config normal_locked_border_color    '#222222'

bspc config auto_cancel		  true
bspc rule -a tilda floating=on focus=on locked=on
bspc rule -a irssi follow=on
bspc rule -a mplayer focus=on
bspc rule -a feh floating=off
bspc rule -a gtksu floating=on
bspc rule -a vlc floating=on
bspc rule -a grub-customizer floating=on
bspc rule -a gparted loating=on
/home/aish/.config/bspwm/panel &
