#! /bin/sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

flavor=${1:-bar}

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#bspc config top_padding $PANEL_HEIGHT

/home/aish/downloads/dzen2_front.sh > "$PANEL_FIFO" &
echo '  ' > "$PANEL_FIFO" &
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &

# conky -c ~/.config/conky/conkyrc > "$PANEL_FIFO" &
/home/aish/downloads/dzen2.sh > "$PANEL_FIFO" &

case "$flavor" in
    bar)
        cat "$PANEL_FIFO" | /home/aish/.config/bspwm/panel_bar | bar &
        ;;
    dzen2)
        . /home/aish/.config/bspwm/panel_colors
        FONT_FAMILY='DejaVu Sans'
        FONT_SIZE=11
        cat "$PANEL_FIFO" | panel_dzen2 -f "$FONT_FAMILY" -s "$FONT_SIZE" | dzen2 -h $PANEL_HEIGHT -dock -ta l -title-name panel -fn "${FONT_FAMILY}:pixelsize=${FONT_SIZE}" -fg "$COLOR_FOREGROUND" -bg "$COLOR_BACKGROUND" &
        ;;
esac

wait
